### ISSUE TITLE
Problem With Input System

### ISSUE THREAD

**Issue by Sahil-Chhoker** [subh05sus/BlockRush-Game#2]
**Describe the bug**
Input system don't work.

**To Reproduce**
1. Create a new project
2. Import this one
3. Press Play

**Expected behavior**
By pressing 'A' and 'D' the plater is supposed to go left and right respectively.

**Desktop:**
 - OS: Windows 11
 - Browser: Brave

**Comment by subh05sus** [comment]
assigned !!
