### ISSUE TITLE
Game Over GUI is not present

### ISSUE THREAD

**Issue by Sahil-Chhoker** [subh05sus/BlockRush-Game#3]
**Describe the bug**
Game Over GUI is not present

**To Reproduce**
1. Open Project
2. Press Play
3. Jump Down the platform

**Expected behavior**
A GUI should be shown with the message "GAME OVER" or something along those lines.

**Desktop:**
 - OS: Windows 11
 - Browser: Brave

**Comment by Sahil-Chhoker** [comment]
I apologize for not working on this as i've got few more issues under the belt and i have to finish them first so can you assign this issue to someone else?

**Comment by subh05sus** [comment]
no, you can work on multiple issues at once, but try to complete them under a week
